[build]
  command = "npm run build"
  publish = ".vinxi/output/public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = ".vinxi/output/server"